import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";

const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mercedes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lora.className} relative`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
